Category.create :name => "白酒"
Category.create :name => "啤酒"
Category.create :name => "洋酒"
Category.create :name => "黄酒"
Category.create :name => "养生酒"
Category.create :name => "收藏酒"
Category.create :name => "陈年老酒"

O2oSetting.province="内蒙古"
O2oSetting.city="赤峰市"
